PP-11678 Update ESlint config to include react files
- Updated ESlint config to include react files and addressed linting issues
- Replaced `tseslint.configs.recommendedTypeChecked` with `tseslint.configs.recommended` config. `recommendedTypeChecked` requires type info, but we don't have types defined consistently across the repo and can't make use of type-aware linting.
- Installed additional dev dependency `@react-spring/rafz` as the compiler is failing to find the module. Failing with the error below:

   ```
	node_modules/@react-spring/shared/dist/react-spring_shared.modern.d.ts:1:27 - error TS2307: Cannot find module '@react-spring/rafz' or its corresponding type declarations.

	1 import { raf, Rafz } from '@react-spring/rafz';
                            ~~~~~~~~~~~~~~~~~~~~
   ```